### ISSUE TITLE
remDr$open does not open a browser window nor does it give an error

### ISSUE THREAD

**Issue by Rez99** [ropensci/RSelenium#275]
### Operating System
OS Name	Microsoft Windows 11 Home

### Selenium Server version (selenium-server-standalone-3.0.1.jar etc.)
java -jar selenium-server-4.8.3.jar standalone

### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
Chrome 111.0.5563.147

### Other driver version (chromedriver 2.27, geckodriver v0.11.1, iedriver x64_3.0.0, PhantomJS 2.1.1 etc.)
Chromedriver 111.0.5563.64

### Expected behaviour
I expect remDr$open() to open a browser window or show an error

### Actual behaviour
I get this output:
[1] "Connecting to remote server"
$id
[1] NA

### Steps to reproduce the behaviour
remDr <-   remoteDriver(
  remoteServerAddr = "localhost",
  port =4444L,
  browserName = "chrome"
)

remDr$open()

- I have confirmed selenium is running by inspecting http://localhost:4444/ui
- If I change the port then remDr$open does show an error (so I don't think this is the problem)

**Comment by jonathanvoelkle** [comment]
Can you try installing the latest version of `wdman` from github? like so: 

```R
# install.packages("remotes")
remotes::install_github("ropensci/wdman")
```

**Comment by showRcd** [comment]
> Can you try installing the latest version of `wdman` from github? like so:
> 
> ```r
> # install.packages("remotes")
> remotes::install_github("ropensci/wdman")
> ```
> 
> that should fix the issue.

I got the same issue, but I did not install the wdman package in the RStudio.

**Comment by jonathanvoelkle** [comment]
`wdman` is a dependency of `RSelenium`; which had some issues with the latest versions of one of the browser drivers. There is a fix on GitHub, which has not yet been published to CRAN, as we haven't done extensive testing.
For that reason, you should try to install the latest version of `wdman` yourself, which (in theory) should fix the issue.
You can do this by running the above-mentioned code. 

Please report again if this does not fix your issue.

**Comment by fvalenduc** [comment]
I have tried the above mentioned steps (using the development version of wdman) , and it still fails like this:

> library(RSelenium)
> 
> remDr <- remoteDriver(
+   remoteServerAddr = "localhost",
+   port =4444L,
+   browserName = "chrome"
+ )
> remDr$open()
[1] "Connecting to remote server"
$id
[1] NA

I run the selenium jar like this: java -jar selenium-server-4.8.3.jar standalone.
Am I doing something wrong ?

**Comment by fvalenduc** [comment]
I am not so sure the problem is caused by a wrong version of wdman. It works fine with the docker images up to selenium 4.8.3. Indeed, it doesn't work anymore with selenium 4.9.0. The changelog says that support for the Json Wire protocol has been removed from selenium grid. Could it be the cause of the problem ?

**Comment by fvalenduc** [comment]
The last version I was able to use outside of the docker images is the 3.141.59 release when a standalone jar was still released. Afterwards, I was never able to use the newer version. I do not know if this is caused by the the selenium server or by the RSelenium package or by the was  I run the selenium webdriver. I always have the problem explained in this bug (no browser opened).

**Comment by fvalenduc** [comment]
This issue is certainly not specific to Windows, I also see this problem on Linux. Can you explain how you managed to use selenium 4.8.3 in Windows without docker ?

**Comment by mwr824** [comment]
> This issue is certainly not specific to Windows, I also see this problem on Linux. Can you explain how you managed to use selenium 4.8.3 in Windows without docker ?

I have clarified my comment. I am using Docker.

**Comment by stevecondylios** [comment]
`remDr$open()` was hanging indefinitely for me:

```R
library(RSelenium)
remDr <- RSelenium::remoteDriver(remoteServerAddr = "localhost",
                                 port = 4445L,
                                 browserName = "chrome")
remDr$open()
[1] "Connecting to remote server"
```

I got it working by using an older version of the selenium/chrome image: `selenium/standalone-chrome:4.2.2`. 

Example:

```sh
docker run -d -p 4445:4444 -v /dev/shm:/dev/shm --platform linux/amd64 selenium/standalone-chrome:4.2.2
```

The idea comes from [here](https://stackoverflow.com/a/76303092/5783745).

**Comment by fvalenduc** [comment]
Of course this works with old version of selenium. But we are then stuck forever with old version of chrome or firefox contained in these docker images. The main problem is that RSelenium doesn't work with versions of selenium newer than 4.8.3.  The changelog for selenium 4.9.0 says that support for the Json Wire protocol has been removed from selenium grid. This is probably the real cause of the problem and there doesn't seem be enthusiasm to adapt RSelenium to this change.

**Comment by mwr824** [comment]
I'll note that I didn't experience this issue on an old machine running Windows 10, if it's helpful for solving the problem.

But color me enthusiastic. I would really like to see this fixed!
